// AUTO-GENERATED by `pnpm generate:templates` — DO NOT EDIT
// Re-run: pnpm generate:templates
import type { TemplateModule, TemplatePreset } from './types';

export const templateMap: Record<string, () => Promise<TemplateModule>> = {
  'cafe-cozy': () => import('./cafe/cozy'),
  'cafe-default': () => import('./cafe/default'),
  'cafe-modern': () => import('./cafe/modern'),
  'corporate-default': () => import('./corporate/default'),
  'corporate-multipage': () => import('./corporate/multipage'),
  'fitness-default': () => import('./fitness/default'),
  'interior-default': () => import('./interior/default'),
  'legal-default': () => import('./legal/default'),
  'medical-default': () => import('./medical/default'),
  'outdoor-default': () => import('./outdoor/default'),
  'wedding-default': () => import('./wedding/default'),
} as const;

export const presetMap: Record<string, () => Promise<{ default: TemplatePreset }>> = {
  'cafe-cozy': () => import('./cafe/cozy/template'),
  'cafe-default': () => import('./cafe/default/template'),
  'cafe-modern': () => import('./cafe/modern/template'),
  'corporate-default': () => import('./corporate/default/template'),
  'corporate-multipage': () => import('./corporate/multipage/template'),
  'fitness-default': () => import('./fitness/default/template'),
  'interior-default': () => import('./interior/default/template'),
  'legal-default': () => import('./legal/default/template'),
  'medical-default': () => import('./medical/default/template'),
  'outdoor-default': () => import('./outdoor/default/template'),
  'wedding-default': () => import('./wedding/default/template'),
} as const;

export const presetSlugs = [
  'cafe-cozy',
  'cafe-default',
  'cafe-modern',
  'corporate-default',
  'corporate-multipage',
  'fitness-default',
  'interior-default',
  'legal-default',
  'medical-default',
  'outdoor-default',
  'wedding-default',
] as const;

/** Maps templateKey → category (derived from directory layout) */
export const templateCategories: Record<string, string> = {
  'cafe-cozy': 'cafe',
  'cafe-default': 'cafe',
  'cafe-modern': 'cafe',
  'corporate-default': 'corporate',
  'corporate-multipage': 'corporate',
  'fitness-default': 'fitness',
  'interior-default': 'interior',
  'legal-default': 'legal',
  'medical-default': 'medical',
  'outdoor-default': 'outdoor',
  'wedding-default': 'wedding',
} as const;

export function getAvailableTemplateKeys(): string[] {
  return Object.keys(templateMap);
}

export function getAvailablePresetKeys(): string[] {
  return Object.keys(presetMap);
}

export function isPresetSlug(slug: string): boolean {
  return (presetSlugs as readonly string[]).includes(slug);
}

export function getCategoryForTemplate(templateKey: string): string | undefined {
  return templateCategories[templateKey];
}
