// AUTO-GENERATED by `pnpm generate:themes` — DO NOT EDIT
// Re-run: pnpm generate:themes
import type { ThemeModule } from './types';

export const themeMap: Record<string, () => Promise<ThemeModule>> = {
  cafe: () => import('./cafe'),
  corporate: () => import('./corporate'),
  fitness: () => import('./fitness'),
  interior: () => import('./interior'),
  legal: () => import('./legal'),
  medical: () => import('./medical'),
  wedding: () => import('./wedding'),
} as const;

export function getAvailableThemeKeys(): string[] {
  return Object.keys(themeMap);
}
