// AUTO-GENERATED by `pnpm generate:themes` — DO NOT EDIT
// Re-run: pnpm generate:themes
import type { ThemeModule, TemplatePreset } from './types';

export const themeMap: Record<string, () => Promise<ThemeModule>> = {
  cafe: () => import('./cafe'),
  corporate: () => import('./corporate'),
  fitness: () => import('./fitness'),
  interior: () => import('./interior'),
  legal: () => import('./legal'),
  medical: () => import('./medical'),
  wedding: () => import('./wedding'),
} as const;

export const presetMap: Record<string, () => Promise<{ default: TemplatePreset }>> = {
  'cafe/cozy': () => import('./cafe/presets/cozy.preset'),
  'cafe/default': () => import('./cafe/presets/default.preset'),
  'cafe/modern': () => import('./cafe/presets/modern.preset'),
  'corporate/default': () => import('./corporate/presets/default.preset'),
  'fitness/default': () => import('./fitness/presets/default.preset'),
  'interior/default': () => import('./interior/presets/default.preset'),
  'legal/default': () => import('./legal/presets/default.preset'),
  'medical/default': () => import('./medical/presets/default.preset'),
  'wedding/default': () => import('./wedding/presets/default.preset'),
} as const;

export const presetSlugs = [
  'cafe-cozy',
  'cafe-default',
  'cafe-modern',
  'corporate-default',
  'fitness-default',
  'interior-default',
  'legal-default',
  'medical-default',
  'wedding-default',
] as const;

export function getAvailableThemeKeys(): string[] {
  return Object.keys(themeMap);
}

export function getAvailablePresetKeys(): string[] {
  return Object.keys(presetMap);
}

export function isPresetSlug(slug: string): boolean {
  return (presetSlugs as readonly string[]).includes(slug);
}
