import { TemplatePreset } from '../../types';

const preset: TemplatePreset = {
  slug: 'fitness-default',
  composition: [
    {
      id: 'nav-001',
      componentKey: 'nav',
      data: {
        brandName: { value: 'APEX', type: 'text', label: '브랜드 이름', editable: true },
        ctaText: { value: '무료 체험', type: 'text', label: 'CTA 텍스트', editable: true },
        menu1: { value: '프로그램', type: 'text', label: '메뉴 1', editable: true },
        menu2: { value: '시설', type: 'text', label: '메뉴 2', editable: true },
        menu3: { value: '트레이너', type: 'text', label: '메뉴 3', editable: true },
        menu4: { value: '후기', type: 'text', label: '메뉴 4', editable: true },
      },
    },
    {
      id: 'hero-001',
      componentKey: 'hero',
      data: {
        label: { value: 'Seoul Gangnam — Since 2010', type: 'text', label: '상단 라벨', editable: true },
        title1: { value: '한계를', type: 'text', label: '타이틀 1행', editable: true },
        title2: { value: '다시', type: 'text', label: '타이틀 2행 (강조)', editable: true },
        title3: { value: '정의합니다', type: 'text', label: '타이틀 3행', editable: true },
        description: { value: '14년의 노하우를 가진 전문 트레이너가 당신만의 목표를 현실로 만들어 드립니다.\n첫 체험은 완전 무료입니다.', type: 'textarea', label: '설명', editable: true },
        backgroundImage: { value: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1600&q=80', type: 'image', label: '배경 이미지', editable: true },
        ctaPrimary: { value: '무료 체험 신청', type: 'text', label: '기본 CTA', editable: true },
        ctaSecondary: { value: '프로그램 보기', type: 'text', label: '보조 CTA', editable: true },
        stat1Value: { value: '1,200', type: 'text', label: '통계 1 수치', editable: true },
        stat1Suffix: { value: '+', type: 'text', label: '통계 1 접미사', editable: true },
        stat1Label: { value: '누적 회원', type: 'text', label: '통계 1 라벨', editable: true },
        stat2Value: { value: '14', type: 'text', label: '통계 2 수치', editable: true },
        stat2Suffix: { value: '년', type: 'text', label: '통계 2 접미사', editable: true },
        stat2Label: { value: '운영 경력', type: 'text', label: '통계 2 라벨', editable: true },
        stat3Value: { value: '32', type: 'text', label: '통계 3 수치', editable: true },
        stat3Suffix: { value: '개', type: 'text', label: '통계 3 접미사', editable: true },
        stat3Label: { value: '주간 클래스', type: 'text', label: '통계 3 라벨', editable: true },
        stat4Value: { value: '98', type: 'text', label: '통계 4 수치', editable: true },
        stat4Suffix: { value: '%', type: 'text', label: '통계 4 접미사', editable: true },
        stat4Label: { value: '목표 달성률', type: 'text', label: '통계 4 라벨', editable: true },
      },
    },
    {
      id: 'marquee-001',
      componentKey: 'marquee',
      data: {
        item1: { value: '퍼스널 트레이닝', type: 'text', label: '항목 1', editable: true },
        item2: { value: '그룹 클래스', type: 'text', label: '항목 2', editable: true },
        item3: { value: '크로스핏', type: 'text', label: '항목 3', editable: true },
        item4: { value: '필라테스', type: 'text', label: '항목 4', editable: true },
        item5: { value: '복싱', type: 'text', label: '항목 5', editable: true },
        item6: { value: '영양 코칭', type: 'text', label: '항목 6', editable: true },
        item7: { value: '재활 운동', type: 'text', label: '항목 7', editable: true },
        item8: { value: '체형 교정', type: 'text', label: '항목 8', editable: true },
      },
    },
    {
      id: 'programs-001',
      componentKey: 'programs',
      data: {
        label: { value: '프로그램', type: 'text', label: '섹션 라벨', editable: true },
        title: { value: '당신의 목표에\n맞는 프로그램', type: 'textarea', label: '섹션 타이틀', editable: true },
        description: { value: '6가지 전문 프로그램으로 체력 강화, 체형 개선, 재활까지 목적에 맞는 트레이닝을 제공합니다.', type: 'textarea', label: '섹션 설명', editable: true },
        p1Title: { value: '퍼스널 트레이닝', type: 'text', label: 'P1 제목', editable: true },
        p1Desc: { value: '1:1 완전 맞춤형 운동 설계 & 집중 케어', type: 'text', label: 'P1 설명', editable: true },
        p1Image: { value: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1100&q=80', type: 'image', label: 'P1 이미지', editable: true },
        p2Title: { value: '크로스핏', type: 'text', label: 'P2 제목', editable: true },
        p2Desc: { value: '기능성 운동의 극한을 경험', type: 'text', label: 'P2 설명', editable: true },
        p2Image: { value: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=700&q=80', type: 'image', label: 'P2 이미지', editable: true },
        p3Title: { value: '복싱', type: 'text', label: 'P3 제목', editable: true },
        p3Desc: { value: '파워와 지구력을 동시에 키우는 실전 복싱', type: 'text', label: 'P3 설명', editable: true },
        p4Title: { value: '필라테스', type: 'text', label: 'P4 제목', editable: true },
        p4Desc: { value: '코어 강화와 유연성을 동시에 잡는 정밀 운동', type: 'text', label: 'P4 설명', editable: true },
        p5Title: { value: '그룹 클래스', type: 'text', label: 'P5 제목', editable: true },
        p5Desc: { value: '함께할 때 더 강해집니다', type: 'text', label: 'P5 설명', editable: true },
        p5Image: { value: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=700&q=80', type: 'image', label: 'P5 이미지', editable: true },
        p6Title: { value: '영양 코칭', type: 'text', label: 'P6 제목', editable: true },
        p6Desc: { value: '식단 전문가의 1:1 맞춤 영양 관리', type: 'text', label: 'P6 설명', editable: true },
      },
    },
    {
      id: 'facility-001',
      componentKey: 'facility',
      data: {
        label: { value: '시설 안내', type: 'text', label: '섹션 라벨', editable: true },
        title: { value: '장비가\n결과를\n만듭니다', type: 'textarea', label: '섹션 타이틀', editable: true },
        description: { value: '500평 규모의 전문 공간에 최신 피트니스 장비가 완비되어 있습니다. 유산소, 웨이트, 기능성 훈련 구역이 명확히 분리되어 집중력 있는 운동이 가능합니다.', type: 'textarea', label: '섹션 설명', editable: true },
        f1Title: { value: '500평 전용 공간', type: 'text', label: '특징 1 제목', editable: true },
        f1Label: { value: 'Facility', type: 'text', label: '특징 1 라벨', editable: true },
        f2Title: { value: '150+ 최신 피트니스 장비', type: 'text', label: '특징 2 제목', editable: true },
        f2Label: { value: 'Equipment', type: 'text', label: '특징 2 라벨', editable: true },
        f3Title: { value: '남녀 전용 샤워 & 사우나', type: 'text', label: '특징 3 제목', editable: true },
        f3Label: { value: 'Locker', type: 'text', label: '특징 3 라벨', editable: true },
        f4Title: { value: '새벽 5시 – 자정 운영', type: 'text', label: '특징 4 제목', editable: true },
        f4Label: { value: 'Hours', type: 'text', label: '특징 4 라벨', editable: true },
        f5Title: { value: '전용 주차 50대 무료', type: 'text', label: '특징 5 제목', editable: true },
        f5Label: { value: 'Parking', type: 'text', label: '특징 5 라벨', editable: true },
        image1: { value: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=600&q=80', type: 'image', label: '이미지 1', editable: true },
        image2: { value: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=600&q=80', type: 'image', label: '이미지 2', editable: true },
        image3: { value: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80', type: 'image', label: '이미지 3', editable: true },
        trustValue: { value: '14', type: 'text', label: '신뢰 지수 수치', editable: true },
        trustLabel: { value: 'Years\nof Trust', type: 'textarea', label: '신뢰 지수 라벨', editable: true },
      },
    },
    {
      id: 'trainers-001',
      componentKey: 'trainers',
      data: {
        label: { value: '트레이너', type: 'text', label: '섹션 라벨', editable: true },
        title: { value: '당신 옆에서\n함께 싸웁니다', type: 'textarea', label: '섹션 타이틀', editable: true },
        description: { value: '국가대표 출신부터 국제 자격증 보유자까지, 검증된 전문가만이 APEX에 있습니다.', type: 'textarea', label: '섹션 설명', editable: true },
        m1Name: { value: '남준혁', type: 'text', label: 'M1 이름', editable: true },
        m1Role: { value: '헤드 코치', type: 'text', label: 'M1 직함', editable: true },
        m1Badge: { value: 'Head Coach', type: 'text', label: 'M1 배지', editable: true },
        m1Image: { value: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?auto=format&fit=crop&w=600&q=80', type: 'image', label: 'M1 사진', editable: true },
        m1Info1: { value: '前 국가대표 역도 선수', type: 'text', label: 'M1 정보 1', editable: true },
        m1Info2: { value: 'NSCA-CSCS 인증', type: 'text', label: 'M1 정보 2', editable: true },
        m1Info3: { value: '트레이닝 경력 13년', type: 'text', label: 'M1 정보 3', editable: true },
        m2Name: { value: '이서현', type: 'text', label: 'M2 이름', editable: true },
        m2Role: { value: '필라테스 · 재활', type: 'text', label: 'M2 직함', editable: true },
        m2Badge: { value: 'Pilates', type: 'text', label: 'M2 배지', editable: true },
        m2Image: { value: 'https://images.unsplash.com/photo-1607962837359-5e7e89f86776?auto=format&fit=crop&w=600&q=80', type: 'image', label: 'M2 사진', editable: true },
        m2Info1: { value: '국제 필라테스 강사 자격 (STOTT)', type: 'text', label: 'M2 정보 1', editable: true },
        m2Info2: { value: '스포츠 재활 전문가', type: 'text', label: 'M2 정보 2', editable: true },
        m2Info3: { value: '트레이닝 경력 9년', type: 'text', label: 'M2 정보 3', editable: true },
        m3Name: { value: '박도현', type: 'text', label: 'M3 이름', editable: true },
        m3Role: { value: '복싱 · 퍼스널', type: 'text', label: 'M3 직함', editable: true },
        m3Badge: { value: 'Boxing', type: 'text', label: 'M3 배지', editable: true },
        m3Image: { value: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80', type: 'image', label: 'M3 사진', editable: true },
        m3Info1: { value: '前 프로 복싱 챔피언', type: 'text', label: 'M3 정보 1', editable: true },
        m3Info2: { value: 'NSCA-CPT & 복싱 공인 코치', type: 'text', label: 'M3 정보 2', editable: true },
        m3Info3: { value: '트레이닝 경력 11년', type: 'text', label: 'M3 정보 3', editable: true },
      },
    },
    {
      id: 'testimonials-001',
      componentKey: 'testimonials',
      data: {
        label: { value: '멤버 후기', type: 'text', label: '섹션 라벨', editable: true },
        title: { value: '결과가\n모든 걸\n말합니다', type: 'textarea', label: '섹션 타이틀', editable: true },
        ratingValue: { value: '4.9', type: 'text', label: '별점 수치', editable: true },
        ratingLabel: { value: 'Google 리뷰 기준 • 894개 후기', type: 'text', label: '별점 라벨', editable: true },
        r1Body: { value: '"3개월 만에 체지방 8% 감소, 근육량 4kg 증가라는 결과를 냈어요. 남준혁 코치님이 제 몸 상태를 완전히 파악하고 주차별로 프로그램을 조정해 주셔서 부상 없이 빠르게 결과를 낼 수 있었습니다."', type: 'textarea', label: '후기 1 본문', editable: true },
        r1Author: { value: '최준서', type: 'text', label: '후기 1 작성자', editable: true },
        r1Meta: { value: '퍼스널 트레이닝 3개월', type: 'text', label: '후기 1 메타', editable: true },
        r2Body: { value: '"허리 디스크로 오래 운동을 못 했는데, 이서현 트레이너님의 재활 필라테스를 시작하고 나서 통증이 60% 이상 줄었어요. 전문적인 지식과 세심한 케어 덕분에 다시 운동할 수 있게 됐습니다."', type: 'textarea', label: '후기 2 본문', editable: true },
        r2Author: { value: '김도연', type: 'text', label: '후기 2 작성자', editable: true },
        r2Meta: { value: '필라테스 & 재활 4개월', type: 'text', label: '후기 2 메타', editable: true },
        r3Body: { value: '"복싱 처음 배울 때 다른 곳에서는 그냥 치는 법만 알려줬는데, 박도현 코치님은 체력 기반부터 탄탄하게 만들어 주셔서 달랐어요. 6개월째 다니고 있는데 스트레스 해소 + 체력 증가 두 마리 토끼를 잡았습니다."', type: 'textarea', label: '후기 3 본문', editable: true },
        r3Author: { value: '오승민', type: 'text', label: '후기 3 작성자', editable: true },
        r3Meta: { value: '복싱 클래스 6개월', type: 'text', label: '후기 3 메타', editable: true },
      },
    },
    {
      id: 'join-001',
      componentKey: 'join',
      data: {
        label: { value: '무료 체험', type: 'text', label: '섹션 라벨', editable: true },
        title1: { value: '지금 시작하면', type: 'text', label: '타이틀 1행', editable: true },
        title2: { value: '첫 주가 무료', type: 'text', label: '타이틀 2행 (강조)', editable: true },
        description: { value: '트레이너 상담부터 시설 이용, 그룹 클래스까지 조건 없이 7일 무료 체험을 제공합니다. 마음에 드셔야 결제하시면 됩니다.', type: 'textarea', label: '설명', editable: true },
        backgroundImage: { value: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1600&q=70', type: 'image', label: '배경 이미지', editable: true },
        phone: { value: '02-555-9876', type: 'text', label: '전화번호', editable: true },
        address: { value: '서울 강남구 역삼동 823-14 B1–2F', type: 'text', label: '위치', editable: true },
        hours: { value: '매일 05:00 – 24:00', type: 'text', label: '운영 시간', editable: true },
      },
    },
    {
      id: 'footer-001',
      componentKey: 'footer',
      data: {
        brandName: { value: 'APEX', type: 'text', label: '브랜드 이름', editable: true },
        brandSubtext: { value: 'Fitness', type: 'text', label: '보조 텍스트', editable: true },
        description: { value: '한계를 다시 정의하는\n강남 프리미엄 피트니스 센터', type: 'textarea', label: '브랜드 설명', editable: true },
        copyright: { value: '© 2024 APEX FITNESS. All rights reserved.', type: 'text', label: '저작권', editable: true },
        businessInfo: { value: '사업자등록번호: 456-78-90123 | 대표: 남준혁', type: 'text', label: '사업자 정보', editable: true },
        address: { value: '서울 강남구 역삼동 823-14\n에이펙스빌딩 B1–2F', type: 'textarea', label: '주소', editable: true },
        phone: { value: '02-555-9876', type: 'text', label: '전화번호', editable: true },
        hours: { value: '평일·주말 05:00 – 24:00\n공휴일 06:00 – 22:00', type: 'textarea', label: '운영 시간', editable: true },
      },
    },
  ],
  thumbnailPath: 'public/thumbnails/template-fitness.webp',
  version: '1.1.0',
  defaults: {
    name: 'Fitness',
    description: '역동적인 피트니스·헬스장 웹사이트 템플릿. 프로그램, 트레이너 소개, 회원권 안내 포함.',
    category: 'health',
  },
};

export default preset;
