#!/usr/bin/env node
// Scans src/themes/*/index.tsx and regenerates src/themes/_generated.ts
// Run: pnpm generate:themes

import { readdirSync, statSync, existsSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const themesDir = join(__dirname, '..', 'src', 'themes');
const outputFile = join(themesDir, '_generated.ts');

const themeKeys = readdirSync(themesDir)
  .filter((entry) => {
    const full = join(themesDir, entry);
    return (
      statSync(full).isDirectory() &&
      existsSync(join(full, 'index.tsx'))
    );
  })
  .sort();

const presets = [];
for (const key of themeKeys) {
  const presetsDir = join(themesDir, key, 'presets');
  if (existsSync(presetsDir)) {
    const files = readdirSync(presetsDir).filter((f) => f.endsWith('.preset.ts'));
    for (const file of files) {
      // e.g. 'cafe' + 'default.preset.ts' -> 'cafe-default' slug-like key
      // but the preset.ts itself has the slug. Here we just need a key for the map.
      // Let's use the filename without .preset.ts for now, or just the full path.
      const presetName = file.replace('.preset.ts', '');
      presets.push({
        theme: key,
        name: presetName,
        importPath: `./${key}/presets/${file.replace('.ts', '')}`,
      });
    }
  }
}

const lines = [
  `// AUTO-GENERATED by \`pnpm generate:themes\` — DO NOT EDIT`,
  `// Re-run: pnpm generate:themes`,
  `import type { ThemeModule, TemplatePreset } from './types';`,
  ``,
  `export const themeMap: Record<string, () => Promise<ThemeModule>> = {`,
  ...themeKeys.map((k) => `  ${k}: () => import('./${k}'),`),
  `} as const;`,
  ``,
  `export const presetMap: Record<string, () => Promise<TemplatePreset>> = {`,
  ...presets.map((p) => `  '${p.theme}/${p.name}': () => import('${p.importPath}'),`),
  `} as const;`,
  ``,
  `export const presetSlugs = [`,
  ...presets.map((p) => `  '${p.theme}-${p.name}',`),
  `] as const;`,
  ``,
  `export function getAvailableThemeKeys(): string[] {`,
  `  return Object.keys(themeMap);`,
  `}`,
  ``,
  `export function getAvailablePresetKeys(): string[] {`,
  `  return Object.keys(presetMap);`,
  `}`,
  ``,
  `export function isPresetSlug(slug: string): boolean {`,
  `  return (presetSlugs as readonly string[]).includes(slug);`,
  `}`,
  ``,
];

writeFileSync(outputFile, lines.join('\n'), 'utf-8');
console.log(`generate:themes — wrote ${themeKeys.length} themes and ${presets.length} presets.`);
