#!/usr/bin/env node
// Scans src/themes/*/index.tsx and regenerates src/themes/_generated.ts
// Run: pnpm generate:themes

import { readdirSync, statSync, existsSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const themesDir = join(__dirname, '..', 'src', 'themes');
const outputFile = join(themesDir, '_generated.ts');

const themeKeys = readdirSync(themesDir)
  .filter((entry) => {
    const full = join(themesDir, entry);
    return (
      statSync(full).isDirectory() &&
      existsSync(join(full, 'index.tsx'))
    );
  })
  .sort();

const lines = [
  `// AUTO-GENERATED by \`pnpm generate:themes\` — DO NOT EDIT`,
  `// Re-run: pnpm generate:themes`,
  `import type { ThemeModule } from './types';`,
  ``,
  `export const themeMap: Record<string, () => Promise<ThemeModule>> = {`,
  ...themeKeys.map((k) => `  ${k}: () => import('./${k}'),`),
  `} as const;`,
  ``,
  `export function getAvailableThemeKeys(): string[] {`,
  `  return Object.keys(themeMap);`,
  `}`,
  ``,
];

writeFileSync(outputFile, lines.join('\n'), 'utf-8');
console.log(`generate:themes — wrote ${themeKeys.length} themes: ${themeKeys.join(', ')}`);
