#!/usr/bin/env node
// Scans src/themes/*/index.tsx and regenerates src/themes/_generated.ts
// Run: pnpm generate:themes
//
// Output schema (post-013): `templateMap`, `getAvailableTemplateKeys`.
// The "templateKey" vocabulary replaces the historical "themeKey".

import { readdirSync, statSync, existsSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const templatesRoot = join(__dirname, '..', 'src', 'themes');
const outputFile = join(templatesRoot, '_generated.ts');

const templateKeys = readdirSync(templatesRoot)
  .filter((entry) => {
    const full = join(templatesRoot, entry);
    return (
      statSync(full).isDirectory() &&
      existsSync(join(full, 'index.tsx'))
    );
  })
  .sort();

const presets = [];
for (const key of templateKeys) {
  const presetsDir = join(templatesRoot, key, 'presets');
  if (existsSync(presetsDir)) {
    const files = readdirSync(presetsDir).filter((f) => f.endsWith('.preset.ts'));
    for (const file of files) {
      const presetName = file.replace('.preset.ts', '');
      presets.push({
        template: key,
        name: presetName,
        importPath: `./${key}/presets/${file.replace('.ts', '')}`,
      });
    }
  }
}

const lines = [
  `// AUTO-GENERATED by \`pnpm generate:themes\` — DO NOT EDIT`,
  `// Re-run: pnpm generate:themes`,
  `import type { TemplateModule, TemplatePreset } from './types';`,
  ``,
  `export const templateMap: Record<string, () => Promise<TemplateModule>> = {`,
  ...templateKeys.map((k) => `  ${k}: () => import('./${k}'),`),
  `} as const;`,
  ``,
  `export const presetMap: Record<string, () => Promise<{ default: TemplatePreset }>> = {`,
  ...presets.map((p) => `  '${p.template}/${p.name}': () => import('${p.importPath}'),`),
  `} as const;`,
  ``,
  `export const presetSlugs = [`,
  ...presets.map((p) => `  '${p.template}-${p.name}',`),
  `] as const;`,
  ``,
  `export function getAvailableTemplateKeys(): string[] {`,
  `  return Object.keys(templateMap);`,
  `}`,
  ``,
  `export function getAvailablePresetKeys(): string[] {`,
  `  return Object.keys(presetMap);`,
  `}`,
  ``,
  `export function isPresetSlug(slug: string): boolean {`,
  `  return (presetSlugs as readonly string[]).includes(slug);`,
  `}`,
  ``,
];

writeFileSync(outputFile, lines.join('\n'), 'utf-8');
console.log(`generate:themes — wrote ${templateKeys.length} templates and ${presets.length} presets.`);
