import { ThemeSlotDefinition } from '../types';
import { TemplateJson } from '@/domain/entities/template.entity';

export const slots: ThemeSlotDefinition[] = [
  { type: 'nav', label: 'Navigation', required: false },
  { type: 'hero', label: 'Hero Section', required: true },
  { type: 'marquee', label: 'Ticker Strip', required: false },
  { type: 'menu', label: 'Menu (Bento)', required: true },
  { type: 'story', label: 'Our Story', required: false },
  { type: 'space', label: 'Space & Features', required: false },
  { type: 'testimonials', label: 'Guest Reviews', required: false },
  { type: 'visit', label: 'Visit Info', required: false },
  { type: 'footer', label: 'Footer', required: false },
];

export const defaultTemplateJson: TemplateJson = {
  themeKey: 'cafe',
  globalStyles: {
    primaryColor: '#C96A3A', // Terra
    secondaryColor: '#231509', // Espresso
    fontFamily: "'Playfair Display', 'Pretendard', sans-serif",
    fontSize: '16px',
    layout: 'wide',
  },
  pages: [
    {
      id: 'home',
      title: 'Home',
      slug: '/',
      order: 0,
      sections: [
        {
          id: 'nav-001',
          type: 'nav',
          order: 0,
          visible: true,
          editable: true,
          data: {
            brandName: { value: 'MONO', type: 'text', label: '브랜드 이름', editable: true },
            brandSubtext: { value: 'Specialty Coffee', type: 'text', label: '보조 텍스트', editable: true },
            menu1: { value: '메뉴', type: 'text', label: '메뉴 1', editable: true },
            menu2: { value: '카페 소개', type: 'text', label: '메뉴 2', editable: true },
            menu3: { value: '공간', type: 'text', label: '메뉴 3', editable: true },
            menu4: { value: '방문 안내', type: 'text', label: '메뉴 4', editable: true },
            ctaText: { value: '오시는 길', type: 'text', label: 'CTA 텍스트', editable: true },
          },
        },
        {
          id: 'hero-001',
          type: 'hero',
          order: 1,
          visible: true,
          editable: true,
          data: {
            label: { value: 'Seoul Seongsu — Specialty Coffee', type: 'text', label: '상단 라벨', editable: true },
            title1: { value: '천천히,', type: 'text', label: '타이틀 1행', editable: true },
            titleAccent: { value: '제대로', type: 'text', label: '강조 타이틀', editable: true },
            subtitle: { value: '— 한 잔의 완성', type: 'text', label: '서브타이틀', editable: true },
            description: { value: '원두 산지부터 로스팅, 추출까지 모든 과정을 직접 관리합니다.\n서두르지 않는 시간 속에서 커피 본연의 맛을 경험하세요.', type: 'textarea', label: '설명', editable: true },
            image: { value: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1100&q=80', type: 'image', label: '배경 이미지', editable: true },
            ctaPrimary: { value: '메뉴 보기', type: 'text', label: '기본 CTA', editable: true },
            ctaSecondary: { value: '카페 소개', type: 'text', label: '보조 CTA', editable: true },
            stat1Value: { value: '07', type: 'text', label: '통계 1 수치', editable: true },
            stat1Label: { value: '년째 운영', type: 'text', label: '통계 1 라벨', editable: true },
            stat2Value: { value: '12', type: 'text', label: '통계 2 수치', editable: true },
            stat2Label: { value: '가지 시그니처', type: 'text', label: '통계 2 라벨', editable: true },
            stat3Value: { value: '4', type: 'text', label: '통계 3 수치', editable: true },
            stat3Label: { value: '곳 원두 산지', type: 'text', label: '통계 3 라벨', editable: true },
            badgeText: { value: '"Roasted in-house"', type: 'text', label: '플로팅 배지 텍스트', editable: true },
            badgeSubtext: { value: '직접 로스팅한 원두', type: 'text', label: '플로팅 배지 보조텍스트', editable: true },
            seasonTag: { value: 'Spring Menu', type: 'text', label: '시즌 태그', editable: true },
          },
        },
        {
          id: 'marquee-001',
          type: 'marquee',
          order: 2,
          visible: true,
          editable: true,
          data: {
            item1: { value: 'Single Origin', type: 'text', label: '항목 1', editable: true },
            item2: { value: '직접 로스팅', type: 'text', label: '항목 2', editable: true },
            item3: { value: '홈메이드 베이커리', type: 'text', label: '항목 3', editable: true },
            item4: { value: 'Specialty Grade', type: 'text', label: '항목 4', editable: true },
            item5: { value: 'No Rush, No Noise', type: 'text', label: '항목 5', editable: true },
            item6: { value: '매일 아침 신선한 원두', type: 'text', label: '항목 6', editable: true },
            item7: { value: 'Slow Coffee Culture', type: 'text', label: '항목 7', editable: true },
          },
        },
        {
          id: 'menu-001',
          type: 'menu',
          order: 3,
          visible: true,
          editable: true,
          data: {
            label: { value: '메뉴', type: 'text', label: '섹션 라벨', editable: true },
            title: { value: '매일 정성껏\n내리는 한 잔', type: 'textarea', label: '섹션 타이틀', editable: true },
            description: { value: '에티오피아, 콜롬비아, 코스타리카, 케냐에서 엄선한 원두를 직접 로스팅합니다.', type: 'textarea', label: '섹션 설명', editable: true },
            p1Badge: { value: 'Signature', type: 'text', label: 'P1 배지', editable: true },
            p1Title: { value: '모노 시그니처 라떼', type: 'text', label: 'P1 제목', editable: true },
            p1Desc: { value: '흑당 카라멜 & 에스프레소의 조화', type: 'text', label: 'P1 설명', editable: true },
            p1Price: { value: '6,500', type: 'text', label: 'P1 가격', editable: true },
            p1Image: { value: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1100&q=80', type: 'image', label: 'P1 이미지', editable: true },
            p2Title: { value: '오늘의 핸드드립', type: 'text', label: 'P2 제목', editable: true },
            p2Desc: { value: '당일 추천 싱글 오리진', type: 'text', label: 'P2 설명', editable: true },
            p2Image: { value: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=700&q=80', type: 'image', label: 'P2 이미지', editable: true },
            p3Title: { value: '에스프레소', type: 'text', label: 'P3 제목', editable: true },
            p3Desc: { value: '원두 본연의 맛을 가장 진하게 느낄 수 있는 기본', type: 'text', label: 'P3 설명', editable: true },
            p3Price: { value: '4,000', type: 'text', label: 'P3 가격', editable: true },
            p4Title: { value: '버터 크루아상', type: 'text', label: 'P4 제목', editable: true },
            p4Desc: { value: '매일 아침 직접 구운 결이 살아있는 크루아상', type: 'text', label: 'P4 설명', editable: true },
            p4Price: { value: '4,500', type: 'text', label: 'P4 가격', editable: true },
            p5Badge: { value: 'Season', type: 'text', label: 'P5 배지', editable: true },
            p5Title: { value: '봄 시즌 드링크', type: 'text', label: 'P5 제목', editable: true },
            p5Desc: { value: '벚꽃 라떼 & 말차 아포가토', type: 'text', label: 'P5 설명', editable: true },
            p5Image: { value: 'https://images.unsplash.com/photo-1542444459-2beac0b15e67?auto=format&fit=crop&w=700&q=80', type: 'image', label: 'P5 이미지', editable: true },
          },
        },
        {
          id: 'story-001',
          type: 'story',
          order: 4,
          visible: true,
          editable: true,
          data: {
            label: { value: '카페 소개', type: 'text', label: '섹션 라벨', editable: true },
            title1: { value: '커피 한 잔에는', type: 'text', label: '타이틀 1행', editable: true },
            titleAccent: { value: '이야기가', type: 'text', label: '강조 타이틀', editable: true },
            title2: { value: '담겨 있습니다', type: 'text', label: '타이틀 2행', editable: true },
            quote: { value: "2017년, 단 하나의 원칙으로 문을 열었습니다. '좋은 커피는 서두르지 않는다.'\n우리는 빠름보다 정확함을, 많음보다 깊음을 선택했습니다.", type: 'textarea', label: '인용구', editable: true },
            description: { value: '에티오피아 예가체프의 플로럴 노트부터 콜롬비아 우일라의 균형 잡힌 바디감까지,\n산지의 특성을 최대한 살린 로스팅으로 커피 본연의 맛을 담아냅니다.', type: 'textarea', label: '설명', editable: true },
            image: { value: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=800&q=80', type: 'image', label: '섹션 이미지', editable: true },
            f1Title: { value: '원두 산지 직거래', type: 'text', label: '특징 1 제목', editable: true },
            f1Desc: { value: '에티오피아, 콜롬비아, 코스타리카, 케냐 농장과 직접 거래해 최상급 원두만을 선별합니다.', type: 'textarea', label: '특징 1 설명', editable: true },
            f2Title: { value: '인하우스 로스팅', type: 'text', label: '특징 2 제목', editable: true },
            f2Desc: { value: '매주 소량씩 직접 로스팅합니다. 항상 최신 로스팅된 신선한 원두만을 사용합니다.', type: 'textarea', label: '특징 2 설명', editable: true },
            f3Title: { value: '홈메이드 베이커리', type: 'text', label: '특징 3 제목', editable: true },
            f3Desc: { value: '매일 새벽 직접 구운 크루아상, 스콘, 마들렌을 커피와 함께 제공합니다.', type: 'textarea', label: '특징 3 설명', editable: true },
          },
        },
        {
          id: 'space-001',
          type: 'space',
          order: 5,
          visible: true,
          editable: true,
          data: {
            label: { value: '공간', type: 'text', label: '섹션 라벨', editable: true },
            title: { value: '머물고 싶은\n공간을 만듭니다', type: 'textarea', label: '섹션 타이틀', editable: true },
            description: { value: '성수동 골목 안 조용한 3층 건물, 각 층마다 다른 분위기로 당신의 시간을 맞이합니다.', type: 'textarea', label: '섹션 설명', editable: true },
            imageLarge: { value: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1000&q=80', type: 'image', label: '큰 이미지', editable: true },
            imageSmall: { value: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=700&q=80', type: 'image', label: '작은 이미지', editable: true },
            cardTitle: { value: '채광이 좋은 공간', type: 'text', label: '카드 제목', editable: true },
            cardDesc: { value: '오전 햇살이 가장 아름답게 드는 남향 창가 자리가 특히 인기입니다.', type: 'textarea', label: '카드 설명', editable: true },
            f1Title: { value: '3층 독립 공간', type: 'text', label: '특징 1 제목', editable: true },
            f1Desc: { value: '층마다 다른 분위기', type: 'text', label: '특징 1 설명', editable: true },
            f2Title: { value: '무료 고속 와이파이', type: 'text', label: '특징 2 제목', editable: true },
            f2Desc: { value: '작업하기 좋은 환경', type: 'text', label: '특징 2 설명', editable: true },
            f3Title: { value: '큐레이션 책장', type: 'text', label: '특징 3 제목', editable: true },
            f3Desc: { value: '커피 & 아트 서적 구비', type: 'text', label: '특징 3 설명', editable: true },
            f4Title: { value: '바이닐 플레이어', type: 'text', label: '특징 4 제목', editable: true },
            f4Desc: { value: '매일 다른 재즈 음악', type: 'text', label: '특징 4 설명', editable: true },
          },
        },
        {
          id: 'testimonials-001',
          type: 'testimonials',
          order: 6,
          visible: true,
          editable: true,
          data: {
            label: { value: '손님 후기', type: 'text', label: '섹션 라벨', editable: true },
            title: { value: '이 공간에서\n느낀 것들', type: 'textarea', label: '섹션 타이틀', editable: true },
            ratingValue: { value: '4.9', type: 'text', label: '별점 수치', editable: true },
            r1Body: { value: '"서울에서 이렇게 조용하고 좋은 커피를 마실 수 있는 곳이 있다는 게 신기해요. 모노 라떼는 단 것을 좋아하지 않아도 먹을 수 있을 만큼 은은하게 달고, 핸드드립은 정말 산지의 특성이 느껴져요."', type: 'textarea', label: '후기 1 본문', editable: true },
            r1Author: { value: '박하린', type: 'text', label: '후기 1 작성자', editable: true },
            r1Meta: { value: '모노 시그니처 라떼', type: 'text', label: '후기 1 메타', editable: true },
            r2Body: { value: '"재택근무할 때 자주 오는데, 분위기가 집중하기 딱 좋아요. 너무 조용하거나 너무 시끄럽지 않고, 와이파이도 빠르고 콘센트도 충분해요. 크루아상이랑 아메리카노 조합이 완벽합니다."', type: 'textarea', label: '후기 2 본문', editable: true },
            r2Author: { value: '류재현', type: 'text', label: '후기 2 작성자', editable: true },
            r2Meta: { value: '작업 겸 방문', type: 'text', label: '후기 2 메타', editable: true },
            r3Body: { value: '"성수동에 카페가 정말 많은데 여기는 진짜 커피 맛으로 승부하는 곳이에요. 스페셜티 커피 처음 입문하시는 분들에게 강력 추천합니다. 바리스타분이 원두 설명도 친절하게 해주셔요."', type: 'textarea', label: '후기 3 본문', editable: true },
            r3Author: { value: '송지안', type: 'text', label: '후기 3 작성자', editable: true },
            r3Meta: { value: '오늘의 핸드드립', type: 'text', label: '후기 3 메타', editable: true },
            r4Body: { value: '"3층 창가 자리에 앉아서 바이닐 음악 들으면서 책 읽었는데 완벽한 오후였어요. 봄 시즌 벚꽃 라떼도 너무 예쁘고 맛있었고, 마들렌은 집에 가져가려고 포장까지 했습니다."', type: 'textarea', label: '후기 4 본문', editable: true },
            r4Author: { value: '김서율', type: 'text', label: '후기 4 작성자', editable: true },
            r4Meta: { value: '봄 시즌 드링크', type: 'text', label: '후기 4 메타', editable: true },
            r5Body: { value: '"에스프레소 마시는 걸 좋아하는데 여기 에스프레소가 서울에서 탑5 안에 든다고 생각해요. 산미와 단맛의 밸런스가 정말 좋고, 추출 시간도 일정하게 유지되는 걸 보면 바리스타분의 실력이 느껴집니다."', type: 'textarea', label: '후기 5 본문', editable: true },
            r5Author: { value: '이준하', type: 'text', label: '후기 5 작성자', editable: true },
            r5Meta: { value: '에스프레소 단골', type: 'text', label: '후기 5 메타', editable: true },
            r6Body: { value: '"성수동 나들이 마지막에 항상 여기서 마무리해요. 원두 소분 판매도 하셔서 집에서도 모노의 맛을 즐길 수 있어요. 선물용으로도 정말 좋아서 지인들한테 많이 선물했습니다."', type: 'textarea', label: '후기 6 본문', editable: true },
            r6Author: { value: '최나은', type: 'text', label: '후기 6 작성자', editable: true },
            r6Meta: { value: '원두 구매 & 카페 이용', type: 'text', label: '후기 6 메타', editable: true },
          },
        },
        {
          id: 'visit-001',
          type: 'visit',
          order: 7,
          visible: true,
          editable: true,
          data: {
            backgroundImage: { value: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1600&q=70', type: 'image', label: '배경 이미지', editable: true },
            label: { value: '방문 안내', type: 'text', label: '섹션 라벨', editable: true },
            title: { value: '언제든\n환영합니다', type: 'textarea', label: '섹션 타이틀', editable: true },
            description: { value: '성수역 2번 출구에서 도보 5분. 붉은 벽돌 건물 1층, 작은 테라스가 있는 곳입니다. 예약 없이 방문하셔도 됩니다.', type: 'textarea', label: '섹션 설명', editable: true },
            phone: { value: '02-499-7788', type: 'text', label: '전화번호', editable: true },
            instagram: { value: '#', type: 'url', label: '인스타그램 링크', editable: true },
            h1Label: { value: '월요일 – 금요일', type: 'text', label: '시간 1 라벨', editable: true },
            h1Value: { value: '08:00 – 21:00', type: 'text', label: '시간 1 수치', editable: true },
            h2Label: { value: '토요일', type: 'text', label: '시간 2 라벨', editable: true },
            h2Value: { value: '09:00 – 22:00', type: 'text', label: '시간 2 수치', editable: true },
            h3Label: { value: '일요일 & 공휴일', type: 'text', label: '시간 3 라벨', editable: true },
            h3Value: { value: '10:00 – 20:00', type: 'text', label: '시간 3 수치', editable: true },
            h4Label: { value: '라스트 오더', type: 'text', label: '시간 4 라벨', editable: true },
            h4Value: { value: '마감 30분 전', type: 'text', label: '시간 4 수치', editable: true },
            address: { value: '서울특별시 성동구 성수동2가 289-12', type: 'text', label: '주소', editable: true },
            addressDetail: { value: '서울숲역 3번 출구 도보 5분\n주차 불가 (성수역 공영주차장 이용)', type: 'textarea', label: '상세 주소/주차', editable: true },
          },
        },
        {
          id: 'footer-001',
          type: 'footer',
          order: 8,
          visible: true,
          editable: true,
          data: {
            brandName: { value: 'MONO', type: 'text', label: '브랜드 이름', editable: true },
            brandSubtext: { value: 'Specialty Coffee & Bakery', type: 'text', label: '브랜드 보조텍스트', editable: true },
            description: { value: '천천히, 제대로.\n성수동에서 한 잔의 완성을 경험하세요.', type: 'textarea', label: '브랜드 설명', editable: true },
            phone: { value: '02-499-7788', type: 'text', label: '전화번호', editable: true },
            address: { value: '서울 성동구 성수동2가 289-12\n서울숲역 3번 출구 5분', type: 'textarea', label: '주소', editable: true },
            weekdayHours: { value: '평일 08:00 – 21:00', type: 'text', label: '평일 영업시간', editable: true },
            weekendHours: { value: '주말·공휴일 09:00 – 22:00', type: 'text', label: '주말 영업시간', editable: true },
            copyright: { value: '© 2024 MONO Specialty Coffee. All rights reserved.', type: 'text', label: '저작권', editable: true },
            businessInfo: { value: '사업자등록번호: 321-98-45678 | 대표: 김지호', type: 'text', label: '사업자 정보', editable: true },
          },
        },
      ],
    },
  ],
};
